### ISSUE TITLE
Normalizing and organizing the project

### ISSUE THREAD

**Issue by shahryarjb** [golobby/orm#9]
Hi folks, 
I wonder why you do not organize this project and do not create some directories to separate it; it would help the developer see this repository clearly. This facility event can help the developer in another language to get information better.

Example like this: https://github.com/elixir-ecto/ecto/tree/master/lib

**Comment by amirrezaask** [comment]
thing is @shahryarjb jan that having it in a flat structure is Go way of doing things because of two reasons
1. In Go directories are packages
2. In Go packages cannot have circular dependencies or duplex dependencies
also there are standard ways of structuring go projects
like https://github.com/golang-standards/project-layout
but since we are just a simple library using that kind of structuring will just move everything into pkg/ subfolder
